version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nest-backend
    env_file:
      - ./.env
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      NODE_ENV: ${NODE_ENV}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
      JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_REGION: ${STORAGE_REGION}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
