export const STORAGE_ENDPOINT = 'STORAGE_ENDPOINT';
export const STORAGE_REGION = 'STORAGE_REGION';
export const STORAGE_BUCKET = 'STORAGE_BUCKET';
export const STORAGE_ACCESS_KEY = 'STORAGE_ACCESS_KEY';
export const STORAGE_SECRET_KEY = 'STORAGE_SECRET_KEY';
